---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dagster
  namespace: production
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: dagster
      version: 0.13.12
  interval: 1m0s
