---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dagster
  # namespace: flux-system
spec:
  chart:
    spec:
      chart: dagster
      sourceRef:
        kind: HelmRepository
        name: staging
      version: 0.13.12
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: flux-system
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: podinfo-values